"""Benchmark construction (the evaluator's side): writes systems.yaml from lab-sim scenario configs.

This script reads the configs' oracle-only ground truth (`LabConfig.resolved_units()`), which run.py
never does. Each system is one scenario, parameter set, and seed, observed through one focal actor: the
frozen component list is the true unit containing that actor (a singleton where no joint unit exists).
Rerun only before a freeze; the output is committed and frozen.

Family mapping (an evaluator judgment, recorded here so it can be disputed):
  distributed-controller     dm_pair, build_loop: actors on separate isolates jointly control releases
  composed-controller        committee_informal_chatter: k reviewer isolates form one decision unit
  external-persistent-state  covert_file_handoff, committee_file: control state carried in shared files
  shared-resources           shared_slot: two engineers share one model slot with no communication
  correlation-not-control    serial_pipeline_no_unit (pipeline neighbours are correlated, not one unit),
                             committee_informal_chatter (chatter on the committee's own channel)
"""

import sys
from pathlib import Path

import yaml

from lab import lab_sim_path

sys.path.insert(0, str(lab_sim_path()))
from lab_sim.harness import ecology  # noqa: E402

SEEDS = range(1, 9)
STATISTIC = ("number of the focal actor's pipeline decisions (build, review vote, release) over the "
             "episode")
SCENARIOS = {
    # name: (factory kwargs, families, focal actor)
    "dm_pair": ({"T": 100}, ["distributed-controller"], "rm1"),
    "build_loop": ({"T": 200}, ["distributed-controller"], "rm1"),
    "committee_informal_chatter": ({"T": 100}, ["composed-controller", "correlation-not-control"], "rev1"),
    "committee_file": ({"T": 100, "channel": "file"}, ["external-persistent-state"], "rev1"),
    "covert_file_handoff": ({"T": 100, "trusting": True}, ["external-persistent-state"], "rev1"),
    "shared_slot": ({"T": 100}, ["shared-resources"], "eng1"),
    "serial_pipeline_no_unit": ({"T": 100}, ["correlation-not-control"], "rm1"),
}
FACTORIES = {
    "dm_pair": ecology.dm_pair_config,
    "build_loop": ecology.build_loop_config,
    "committee_informal_chatter": ecology.committee_with_informal_chatter_config,
    "committee_file": ecology.committee_config,
    "covert_file_handoff": ecology.covert_file_handoff_config,
    "shared_slot": ecology.shared_slot_config,
    "serial_pipeline_no_unit": ecology.serial_pipeline_no_unit_config,
}


def main():
    systems = []
    for name, (params, families, focal) in SCENARIOS.items():
        units = FACTORIES[name](**params).resolved_units()
        unit = next((sorted(m) for m in units.values() if focal in m), [focal])
        for seed in SEEDS:
            systems.append({
                "id": f"{name}-s{seed}", "scenario": name, "params": dict(params), "seed": seed, "focal": focal,
                "families": list(families), "adversarial_subset": False, "components": list(unit),
                "response_statistic": STATISTIC, "min_change": 1.0, "no_effect_range": [-0.5, 0.5],
            })
    out = Path(__file__).with_name("systems.yaml")
    header = ("# Generated by build_systems.py from lab-sim scenario configs (oracle ground truth). Frozen by\n"
              "# `workbench freeze`; edit build_systems.py and regenerate before a freeze, never after.\n")
    out.write_text(header + yaml.safe_dump({"systems": systems}, sort_keys=False, width=110), encoding="utf-8")
    print(f"wrote {len(systems)} systems to {out}")


if __name__ == "__main__":
    main()
